apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d7eqm8tl5-python
  janus-idp.io/tekton: d7eqm8tl5-python
  backstage.io/kubernetes-id: d7eqm8tl5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d7eqm8tl5-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
